### USER REGISTER
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
    "name": "dhairya",
    "email": "dhairya@gmail.com",
    "password": "dhairya"
}

### USER LOGIN
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
    "email": "pranay@gmail.com",
    "password": "pranay"
}

### USER LOGOUT
GET http://localhost:8080/api/auth/logout

// update and delete should be present in /api/user/profile (can be fixed later if needed)
### USER UPDATE 
PUT http://localhost:8080/api/auth/profile
Content-Type: application/json

{
    "name": "user1",
    "email": "user1@example.com",
    "password": "user1",
    "userProfile":""
}


### USER DELETE
DELETE http://localhost:8080/api/auth/profile
Content-Type: application/json

{
    "password": "user1"
}


