### Create a new branch
POST http://localhost:8080/api/branches/branch
Content-Type: application/json

{
    "name": "main",
    "repoId": "6a04843566052ca9632349b7"
}

### Get all branches in a repository using repoId
GET http://localhost:8080/api/branches/repo/6a04843566052ca9632349b7

### Get a branch by branchId
GET http://localhost:8080/api/branches/branch/6a02dfd46ff6de77bb6dd361

### Get a branch using branch name from a repository
GET http://localhost:8080/api/branches/repo/6a02e3cc09325ae118e03f89/branch/feature-auth
