### Adding a new collaborator to a repository
POST http://localhost:8080/api/collaborator/new
Content-Type: application/json

{
    "repoId": "69fc62f6cd7532dfecc4bbc5",
    "userId": "69f9a013a02dd7672c943f3c",
    "role": "collaborator"
}