### Adding a new collaborator to a repository
POST http://localhost:8080/api/collaborator/new
Content-Type: application/json

{
    "repoId": "69ff5cf177314de2c408bef7",
    "userId": "69fda478a63e1422a85c3450",
    "role": "collaborator"
}

### get all collaborators by repoId
GET http://localhost:8080/api/collaborator/collabs/69ff5d0377314de2c408bef8

### Get a collaborator using collabId
GET http://localhost:8080/api/collaborator/collab/69ff5e8277314de2c408befb

### update
PUT http://localhost:8080/api/collaborator/collab/69ff5e8277314de2c408befb
Content-Type: application/json

{
    "repoId": "69ff5d0377314de2c408bef8",
    "userId": "69fda478a63e1422a85c3450",
    "role": "collaborator"
}

### Remove role of a user using repoId and userId
DELETE http://localhost:8080/api/collaborator/repos/69ff5d0377314de2c408bef8/collab/69ff5e8277314de2c408befb

### Deleting collaborator using collabId
DELETE http://localhost:8080/api/collaborator/collab/69ff5e8277314de2c408befb