### Create a new commit
POST http://localhost:8080/api/commits/commit
Content-Type: application/json

{
    "repository": "6a02df766ff6de77bb6dd360",
    "message": "updated file1.txt",
    "files": ["6a02e4ea09325ae118e03f8c"]
}

### Get all commits by repoId
GET http://localhost:8080/api/commits/repo/6a02df766ff6de77bb6dd360

### Get a commit by commitId
GET http://localhost:8080/api/commits/commit/6a02eb6534318682d0e438ca

