### Create a new file
POST http://localhost:8080/api/files/file
Content-Type: application/json

{
    "name": "file3.txt",
    "content": "This is the content of file.",
    "repoId": "69fc602f336607d0f0c709d2"
}

### Edit an existing file
PUT http://localhost:8080/api/files/file/69fc602f336607d0f0c709d3
Content-Type: application/json

{
    "name": "file3.txt",
    "content": "This is the updated content of file.",
    "repoId": "69fc602f336607d0f0c709d2"
}

### Update file by id
PUT http://localhost:8080/api/files/file/69fc602f336607d0f0c709d3
Content-Type: application/json

{
    "repoId": "69fc602f336607d0f0c709d2",
    "name": "file3.txt",
    "content": "This is the updated content of file."
}

### Soft delete a file
PUT http://localhost:8080/api/files/file/delete-toggle
Content-Type: application/json

{
    "fileId": "69fc602f336607d0f0c709d3",
    "repoId": "69fc602f336607d0f0c709d2",
    "isDeleted": true
}

### Get a file by id
GET http://localhost:8080/api/files/file/69fc602f336607d0f0c709d3


### Get all files in a repository   
GET http://localhost:8080/api/files/repo/69fc602f336607d0f0c709d2