### creating new repository
POST http://localhost:8080/api/repository/repo
Content-Type: application/json

{
    "name": "private-repo",
    "description": "this is a private repo created by user1, collaborating with user2",
    "visibility": "PRIVATE"
}

### getting repository by id
GET http://localhost:8080/api/repository/repo/69fc562c03a186f0e0a02538

### Searching repositories by name
GET http://localhost:8080/api/repository/search?repoName=r

### Updating repository by id
PUT http://localhost:8080/api/repository/repo/69fc62f6cd7532dfecc4bbc5
Content-Type: application/json

{
    "name": "repo1-updated",
    "description": "this is repo1-updated",
    "visibility": "PUBLIC"
}

### Deleting repository by id
DELETE http://localhost:8080/api/repository/repo/69fc62f6cd7532dfecc4bbc5

### getting all repositories
GET http://localhost:8080/api/repository/all-repos



