### creating new repository
POST http://localhost:8080/api/repository/repo
Content-Type: application/json

{
    "name": "repository-1",
    "description": "this is a public repository-1 created by user1",
    "visibility": "PUBLIC"
}

### getting repository by id
GET http://localhost:8080/api/repository/repo/69ff5d0377314de2c408bef8

### Searching repositories by name
GET http://localhost:8080/api/repository/search?repoName=re

### Updating repository by id
PUT http://localhost:8080/api/repository/repo
Content-Type: application/json

{
    "repoId":"69ff5c18d70ad9a6262bdc56",
    "name": "private-repo1",
    "description": "this is a private repo 1 created by user1",
    "visibility": "PRIVATE"
}

### Deleting repository by id
DELETE http://localhost:8080/api/repository/repo/6a0594a805546ab2fcae09f3

### getting all repositories
GET http://localhost:8080/api/repository/all-repos



