### GET USER PROFILE
GET http://localhost:8080/api/users/profile


### SEARCH USER BY ID
GET http://localhost:8080/api/users/user/69f9a013a02dd7672c943f3c

### SEARCH USER BY NAME
GET http://localhost:8080/api/users/search?name=user

### SEARCH USER BY EMAIL
GET http://localhost:8080/api/users/search?email=user1@example.com